ec2_burstable_instances = {
    "t2.nano": {
        "cpu_credits_per_hour": 3,
        "max_cpu_credits": 72,
        "vCPUs": 1,
        "baseline": 5,
    },
    "t2.micro": {
        "cpu_credits_per_hour": 6,
        "max_cpu_credits": 144,
        "vCPUs": 1,
        "baseline": 10,
    },
    "t2.small": {
        "cpu_credits_per_hour": 12,
        "max_cpu_credits": 288,
        "vCPUs": 1,
        "baseline": 20,
    },
    "t2.medium": {
        "cpu_credits_per_hour": 24,
        "max_cpu_credits": 576,
        "vCPUs": 2,
        "baseline": 20,
    },
    "t2.large": {
        "cpu_credits_per_hour": 36,
        "max_cpu_credits": 864,
        "vCPUs": 2,
        "baseline": 30,
    },
    "t2.xlarge": {
        "cpu_credits_per_hour": 54,
        "max_cpu_credits": 1296,
        "vCPUs": 4,
        "baseline": 22.5,
    },
    "t2.2xlarge": {
        "cpu_credits_per_hour": 81.6,
        "max_cpu_credits": 1958.4,
        "vCPUs": 8,
        "baseline": 17,
    },
    "t3.nano": {
        "cpu_credits_per_hour": 6,
        "max_cpu_credits": 144,
        "vCPUs": 2,
        "baseline": 5,
    },
    "t3.micro": {
        "cpu_credits_per_hour": 12,
        "max_cpu_credits": 288,
        "vCPUs": 2,
        "baseline": 10,
    },
    "t3.small": {
        "cpu_credits_per_hour": 24,
        "max_cpu_credits": 576,
        "vCPUs": 2,
        "baseline": 20,
    },
    "t3.medium": {
        "cpu_credits_per_hour": 24,
        "max_cpu_credits": 576,
        "vCPUs": 2,
        "baseline": 20,
    },
    "t3.large": {
        "cpu_credits_per_hour": 36,
        "max_cpu_credits": 864,
        "vCPUs": 2,
        "baseline": 30,
    },
    "t3.xlarge": {
        "cpu_credits_per_hour": 96,
        "max_cpu_credits": 2304,
        "vCPUs": 4,
        "baseline": 40,
    },
    "t3.2xlarge": {
        "cpu_credits_per_hour": 192,
        "max_cpu_credits": 4608,
        "vCPUs": 8,
        "baseline": 40,
    },
    "t3a.nano": {
        "cpu_credits_per_hour": 6,
        "max_cpu_credits": 144,
        "vCPUs": 2,
        "baseline": 5,
    },
    "t3a.micro": {
        "cpu_credits_per_hour": 12,
        "max_cpu_credits": 288,
        "vCPUs": 2,
        "baseline": 10,
    },
    "t3a.small": {
        "cpu_credits_per_hour": 24,
        "max_cpu_credits": 576,
        "vCPUs": 2,
        "baseline": 20,
    },
    "t3a.medium": {
        "cpu_credits_per_hour": 24,
        "max_cpu_credits": 576,
        "vCPUs": 2,
        "baseline": 20,
    },
    "t3a.large": {
        "cpu_credits_per_hour": 36,
        "max_cpu_credits": 864,
        "vCPUs": 2,
        "baseline": 30,
    },
    "t3a.xlarge": {
        "cpu_credits_per_hour": 96,
        "max_cpu_credits": 2304,
        "vCPUs": 4,
        "baseline": 40,
    },
    "t3a.2xlarge": {
        "cpu_credits_per_hour": 192,
        "max_cpu_credits": 4608,
        "vCPUs": 8,
        "baseline": 40,
    },
    "t4g.nano": {
        "cpu_credits_per_hour": 6,
        "max_cpu_credits": 144,
        "vCPUs": 2,
        "baseline": 5,
    },
    "t4g.micro": {
        "cpu_credits_per_hour": 12,
        "max_cpu_credits": 288,
        "vCPUs": 2,
        "baseline": 10,
    },
    "t4g.small": {
        "cpu_credits_per_hour": 24,
        "max_cpu_credits": 576,
        "vCPUs": 2,
        "baseline": 20,
    },
    "t4g.medium": {
        "cpu_credits_per_hour": 24,
        "max_cpu_credits": 576,
        "vCPUs": 2,
        "baseline": 20,
    },
    "t4g.large": {
        "cpu_credits_per_hour": 36,
        "max_cpu_credits": 864,
        "vCPUs": 2,
        "baseline": 30,
    },
    "t4g.xlarge": {
        "cpu_credits_per_hour": 96,
        "max_cpu_credits": 2304,
        "vCPUs": 4,
        "baseline": 40,
    },
    "t4g.2xlarge": {
        "cpu_credits_per_hour": 192,
        "max_cpu_credits": 4608,
        "vCPUs": 8,
        "baseline": 40,
    },
}
